name: laundrymart
description: A new Flutter project.

publish_to: "none"

version: 1.3.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI & Layout
  flutter_screenutil: ^5.9.0
  page_transition: ^2.0.9
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5
  expandable: ^5.0.1
  percent_indicator: ^4.2.3
  timeline_tile: ^2.0.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.8

  # State management
  flutter_riverpod: ^2.1.3
  riverpod: ^2.3.2
  freezed_annotation: ^2.2.0

  # Network & HTTP
  dio: ^5.3.3
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.6

  # Firebase
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.1
  # flutter_local_notifications: ^16.3.3
  # flutter_svg: ^2.0.7
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Device & Permissions
  location: ^5.0.3
  permission_handler: ^11.0.0
  device_info_plus: ^9.1.1
  open_file: ^3.3.2
  lite_rolling_switch: ^1.0.1

  # Media & Images
  image_picker: ^1.0.4
  signature: ^5.3.0
  flutter_pdfview: ^1.2.5

  # Utility
  logger: ^2.0.2+1
  upgrader: ^8.2.0
  rename: ^3.0.1
  readmore: ^2.2.0
  country_picker: ^2.0.20
  curved_navigation_bar: ^1.0.3
  awesome_snackbar_content: ^0.1.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  pin_code_fields: ^8.0.1
  flutter_html: ^3.0.0
  custom_info_window: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_polyline_points: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/playstore.png" # <-- Updated for Play Store image
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/png/playstore.png"

flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.20.2
